### ISSUE TITLE
normalize is take some time if object has more number of keys.

### ISSUE THREAD

**Issue by vimalceg** [paularmstrong/normalizr#126]
# Problem

normalization is take some time if object has more number of keys.  I tried with array has 100 object and each object has 30 keys and mapping with two nested schema. It takes around ~25ms. I tried using schema based iteration it takes ~7ms. I don't know, Is any problem using schema based iteration? Please refer the link below.

https://github.com/vimalceg/normalizr

**Comment by paularmstrong** [comment]
Unless you have a perf test (I didn't see one) the difference between 7 and 25ms could be due to many other factors like CPU usage, memory available, etc. Keep in mind that normalizr walks the entire schema structure, so it'll take longer the more complex your schema is and/or the more data that you give it.

I don't understand what you're trying to show in the code you posted. Do you have a perf test?

**Comment by vimalceg** [comment]
In the code, I tried normalization conversion in different way. First I read the schema mapping, If schema has any *mapping then complete nested normalization first. (mapping means relationship between entities one to one, one to many). This is reduce the time. 

In the below example 

- 100 tickets information(entities)
- each ticket has one contact information(entity)
- each contact has one account 
- all entity object has 50 keys

https://vimalceg.github.io

**Comment by paularmstrong** [comment]
If you'd like to open a PR that passes all tests and makes things faster, I'd love to see that!
