### ISSUE TITLE
[QUESTION] Normalize nested object

### ISSUE THREAD

**Issue by TryingToImprove** [paularmstrong/normalizr#134]
# Question

I have a schema like this:

``` js
{ 
   id: 1,
   name: 'TryingToImprove',
   relations: [
     {
       type: 'foo',
       person: { id: 1, title: 'foofoo' }
     },
     {
       type: 'bar',
       person: { id: 2, title: 'barbar' }
     }
   ]
}
```

Which I can normalize this to:

``` js
{
  entities: { 
    users: { 
      "1": { id: 1, name: 'TryingToImprove', relations: [{type: 'foo', person: 1 }, {type: 'bar', person: 2 }] }
    },
    persons: {
      "1": { id: 1, title: 'foofoo' },
      "2": { id: 2, title: 'barbar' }
    }
  },
  result: { users: [1], persons: [1, 2] }
}
```

But when I call my AJAX services I only get the userId, and the new relation. Is there a way to instead of mapping it to above, then map it to something like this:

``` js
{
  entities: { 
    users: { 
      "1": { id: 1, name: 'TryingToImprove' }
    },
    userRelations: {
      "1": [{type: 'foo', person: 1 }, {type: 'foo', person: 2 }]
    },
    persons: {
      "1": { id: 1, title: 'foofoo' },
      "2": { id: 2, title: 'barbar' }
    }
  },
  result: { users: [1], persons: [1] }
}
```

where the `1` in `userRelations` is the userId

**NOTE:** My relations does not have a id, and are coupled to the user, so if I know the userId I would be able to get the userRelations.

This should make it possible for me to map: 

``` js
{
   id: 1,
   relations: [{
     type: 'foo',
     person: { id: 2, title: 'bar' }
  }]
}
```

without changing the `user.relation`

**Comment by TryingToImprove** [comment]
I have created a PR for this: #135

**Comment by marceux** [comment]
I hope you get a response and a recommendation soon, because I feel like one of my cases matches yours.

**Comment by paularmstrong** [comment]
Why is the normalized result not sufficient?

**Comment by marceux** [comment]
@paularmstrong I'm going to chime in because I need help in simply understanding how I can do something similar.

Is the normalized result sufficient? I thought the point of normalization was to minimize data redundancy and (in the case of the state) object nesting.

I think @TryingToImprove (and I may be wrong) is trying to add in an associative entity (`userRelations`) that describes the relationship between `users` and `persons` with an additional attribute to boot.

In doing so it looks like he wants to avoid including relation information within `users` objects.

Is it wrong to do so?

I read somewhere that with normalization we're approaching (or lightly mimicking) the behavior of a relational database, and it makes sense to want to isolate associative relations. The problem is that sometimes these relations do not carry unique identifiers. How do we work with them then?

**Comment by TryingToImprove** [comment]
@marceux described it perfectly.. :+1:  My `UserRelations` does not have a id, because it is a nested object in my NoSQL document. I think having the relationship in the normalized result helps me easily add or remove `userRelations`.

**Comment by paularmstrong** [comment]
I think you guys might be overcomplicating things. Why do you need a separate relationship object when it's already embedded in the object itself? The current method prevents you from needing to extract that information and merge it back in ever.

If you want true relations, we would need to revive #80 and make that work correctly.

**Comment by marceux** [comment]
I think a separate relationship object is helpful when the relationship has its own attributes (in this topic's example, that would be the `type` field).

For relationships with unique identifiers, this is easy as we would treat it like a separate entity.

My issue is that I wanted to know what is *correct*-ish when the relationship does **not** have any unique identifiers and has its own attributes. Embedding the relationship within one of the associated entities feels bulky and runs counter to normalization (at least for me) because it's a nested object. But if I'm over-thinking it, I'll just move forward with working with it as-is, and calling it a day.

---

Side-note, @TryingToImprove. Why not try:

```
{
  entities: { 
    users: { 
      "1": { id: 1, name: 'TryingToImprove'},
      "typeByPerson": {
        "1": 'foo',
        "2": 'bar',
    },
    persons: {
      "1": { id: 1, title: 'foofoo' },
      "2": { id: 2, title: 'barbar' }
    }
  },
  result: { users: [1], persons: [1, 2] }
}
```
