### ISSUE TITLE
Should there be an empty object when normalizing empty array?

### ISSUE THREAD

**Issue by mockdeep** [paularmstrong/normalizr#270]
# Problem

When I'm normalizing an empty collection, the key under `entities` for that collection comes back `undefined`, rather than an empty object, which is more what I'd expect.

**Input**

```js
var taskSchema = new schema.Entity('tasks')
var taskListSchema = new schema.Array(taskSchema)
normalize([], taskListSchema)
```

**Output**

Here's what I expect to see when I run the above:

```js
{
  entities: {tasks: {}},
  result: []
}
```

Here's what I *actually* see when I run the above:

```js
{
  entities: {},
  result: []
}
```

This means in my code I need to have an extra check for `undefined` instead of being able to transparently treat the nested entity like an object in all cases.

**Comment by jraut** [comment]
Instead of checking for values in entities, you could do things based on `results`. 

Your solution is cumbersome in bigger projects since results carry lots of noise without proper content. I'd rather not initialize empty variables/properties.

**Comment by mockdeep** [comment]
@jraut can you tell me more about how it becomes cumbersome in bigger projects? I'm not sure I understand.

In our case, we like to reduce conditional logic by being able to treat things as always the same type. If I'm passing in a `tasks` schema, then it would be nice to always have a `tasks` object, even an empty one, under `entities`. Checking the length of `result` or the presence of the key under `entities` amounts to much the same in that regard.

**Comment by paularmstrong** [comment]
This is the expected response for `normalize`, as written. It's much more simple as-is and shouldn't require hard work on your end to account for entities that were not found in the normalization process.

If we were to make the change per your suggestion, we would first have to initialize `entities` based on the entire schema tree provided, like this:

```js
const group = schema.Entity('groups');
const user = schema.Entity('users', { groups: [ group ] });
const comment = schema.Entity('comments', { user });
const article = schema.Entity('articles', { user, comments: [ comment ] });

normalize([], [ article ]);

// ...

{
  entities: {
    groups: {},
    users: {},
    comments: {},
    articles: {}
  },
  result: []
}
```

Which is just not really feasible, since the normalization process happens on an as-needed basis as each key/object is found. This would be a substantial change that would need to first initialize the `entities` object before any real normalization has started.

I'm going to mark as "won't fix", since this seems very much "nice to have" and not really a problem.
