### ISSUE TITLE
Add ability to pass down additional information to `processStrategy`

### ISSUE THREAD

**Issue by richardson-trevor** [paularmstrong/normalizr#310]
# Problem
There are times when I need information about ancestors higher than a parent when I'm processing a given schema using the `processStrategy`. 

# Current Solution
One technique that we can currently use to do this sort of thing is to map the additional information into the resulting value response from the `processStrategy`. This way the child can look at the `parent` arg in its `processStrategy`. The downside of this is that the additional 'pass-through' information gets mapped into the ancestor's entity result after normalization. 

# Desired Result
It would instead be nice to be able to pass down arbitrary information to descendants as they are being processed.

An example implementation of what I'm looking to do can be found in [this StackOverflow question](https://stackoverflow.com/questions/47535589/accessing-parent-properties-from-processstrategy).

**Comment by travi** [comment]
Having gone another step with our work-around, we've realized an additional complication. With the additional layer that is created, the relationship between the intended parent and child is broken. 

In order to restore the relationship, we would need to map some sort of an `id` property into the meaningless intermediate layer so that we could relate the original layers back to each other by hopping through that intermediate layer.

Since dealing with the intermediate layer is a bit of a hack to work around the fact that the shorthand syntax defines an additional schema rather than describing a nested property as the child wasn't obvious, I think I'm mostly curious if there is a correct way to describe the structure for shapes like ours where the child is not a top-level property. If there isn't currently, would you be open to enabling something along those lines?

The reason for the shape we are working with is because we follow the [HAL spec](https://tools.ietf.org/html/draft-kelly-json-hal-08) for our API and embedded resources are named under the top-level `_embedded`. This is always the case for us, but outside of that difference from the `normalizr` standard use-case, `normalizr` is a great solution for our need.

**Comment by paularmstrong** [comment]
I think this would complicate normalizr too much. Feel free to fork and add what you need into a separate package.
