### ISSUE TITLE
object nomaliser is not working.....

### ISSUE THREAD

**Issue by skptricks** [paularmstrong/normalizr#362]
not able to normalize json data. could you please check once ....

const blogPosts = [
  {
    id: 'post1',
    author: { username: 'user1', name: 'User 1' },
    body: '......',
    comments: [
      {
        id: 'comment1',
        author: { username: 'user2', name: 'User 2' },
        comment: '.....'
      },
      {
        id: 'comment2',
        author: { username: 'user3', name: 'User 3' },
        comment: '.....'
      }
    ]
  },
  {
    id: 'post2',
    author: { username: 'user2', name: 'User 2' },
    body: '......',
    comments: [
      {
        id: 'comment3',
        author: { username: 'user3', name: 'User 3' },
        comment: '.....'
      },
      {
        id: 'comment4',
        author: { username: 'user1', name: 'User 1' },
        comment: '.....'
      },
      {
        id: 'comment5',
        author: { username: 'user3', name: 'User 3' },
        comment: '.....'
      }
    ]
  }
  
]
const user = new schema.Entity('user');
const author = new schema.Entity('author',{
  author: user
});
const comment = new schema.Entity('comments',{
  author: user,
 
});
const post = new schema.Entity('post',{
  author: user,
  comments: [comment]
});

const normalizedDatea = normalize(blogPosts,  post );
console.log(normalizedDatea);

**Comment by thib92** [comment]
Hey 👋 

You have two issues in your example.
First off, your `user` entity does not have an `id` attribute. This means that `normalize` will not be able to index it by its id.

You can change your `user` schema definition to take another field as its id. For example `username`, like this:

```js
const user = new schema.Entity('user', {}, {
  idAttribute: 'username'
});
```

The second issue is that the second parameter to the `normalize` function is the schema of the root object you want to normalize. Here, you are trying to normalize an array of `post`, not a single `post`.

So you need to do the following:

```js
const normalizedDatea = normalize(blogPosts, [post]);
```

Notice that I use `[post]` instead of `post`.

By the way, I believe this kind of questions should go on Stackoverflow, not in the Issues section of the package, as this is not a bug from the package. Final note, when giving your code (which is a good think), please use backticks to have syntax highlight and correct indentation, as it's much easier to read 😄
