### ISSUE TITLE
null value from key parameter of processStrategy function

### ISSUE THREAD

**Issue by yipivan** [paularmstrong/normalizr#371]
I tried to reconstruct the data in the way I wanted and this includes the index of the entity in the parent array, but I always get back null from the `processStrategy` function when i try to read the `key` from the function, which I dunno if its a bug or not.

consider this sandbox which I just copied the example from api doc:
https://codesandbox.io/s/zl4o54q0mx

**Comment by paularmstrong** [comment]
a `null` key makes sense in your repro, because the `tweet` is the top-level object and it has no parent key at which it is found.

If your incoming data were structured differently, it reports correctly, as far as I can tell. For example: 

```js
normalize({ a: data }, { a: tweet });
>> a
```

Please reopen if you find a different case where this does not work as expected
