### ISSUE TITLE
Difference from 3.4.1 -> 3.5.0

### ISSUE THREAD

**Issue by fayebutler** [paularmstrong/normalizr#433]
# Update from 3.4.1 to 3.5.0 breaks my nested schema

Got to say this library is great and maybe I just need some more documentation on different releases.
I generate ID's within the processStrategy function, they seem to be set okay but in nested schema they come up as undefined. 

For example: 

I have set up a simple version of my schema and data, in the sandbox it works with version 3.4.1 and doesn't with 3.5.0.

https://codesandbox.io/s/normalizr-test-case-1vro8

Example result:

Expected:
```JSON{
  "entities": {
    "noteSegments": {
      "_43lpgiowz": {
        "id": "_43lpgiowz",
        "text": "hello"
      },
      "_sllb4dj34": {
        "id": "_sllb4dj34",
        "text": "world"
      }
    },
    "notes": {
      "_ed18968mp": {
        "id": "_ed18968mp",
        "note": [
          "_43lpgiowz",
          "_sllb4dj34"
        ]
      }
    },
    "sections": {
      "_zwsc0wqz8": {
        "id": "_zwsc0wqz8",
        "index": 0,
        "notes": [
          "_ed18968mp"
        ]
      }
    }
  },
  "result": [
   "_zwsc0wqz8"
  ]
}
```

Actual:
```JSON{
  "entities": {
    "noteSegments": {
      "_43lpgiowz": {
        "id": "_43lpgiowz",
        "text": "hello"
      },
      "_sllb4dj34": {
        "id": "_sllb4dj34",
        "text": "world"
      }
    },
    "notes": {
      "_ed18968mp": {
        "id": "_ed18968mp",
        "note": [
          undefined,
          undefined
        ]
      }
    },
    "sections": {
      "_zwsc0wqz8": {
        "id": "_zwsc0wqz8",
        "index": 0,
        "notes": [
          undefined
        ]
      }
    }
  },
  "result": [
    undefined
  ]
}
```

**Comment by febeck** [comment]
Yes, I'm having the same issue as @fayebutler  and loose the reference to the element that had a `processStrategy`

**Comment by p-j** [comment]
@fayebutler @febeck Looking at your example and at the diff (https://github.com/paularmstrong/normalizr/compare/v3.4.1...v3.5.0#diff-0259e620a36a18bc8e8a06f1bf5b180dL51-L67)

It seems the issue is with setting ids directly to the passed object, which is passed by reference (as it is not a primitive).

Before the update, that would "work" because the call to `getId` is done after `processStrategy` and since the `input` has been mutated to add the `id` parameter; it is found by `getId`.

In the diff we can see that the call to `getId` is now done before `processStrategy` so relying on mutating the `input` doesn't work anymore.

What works though, both in the previous and the current version, is using the provided `idAttribute` API to set the id for your entity.

I've adapted your code here to show how it would work: https://codesandbox.io/s/normalizr-test-case-kvt7d

Hope this helps

**Comment by fayebutler** [comment]
I see, thanks for explaining that! 
Is there another place where you can add an "id" attribute onto the entity? Or do I have to loop through and add the IDs before I normalize the data? 
The way you've described in the sandbox works but it doesn't actually match up the nested entities with the correct ID since they generate a new ID every time.

**Comment by p-j** [comment]
I don't know your exact setup and we don't work with random ids generated on the fly on our end.
Either ids are given and maintained by our backend or ids are derived from unique set of properties of our entity, like a composite key in SQL, which make them predictable and reproductible.
So I guess you either have to loop over your data and/or use a function that can create a stable unique identifier for your data.
Maybe you can check [object-hash](https://www.npmjs.com/package/object-hash) if you are looking for a generic solution, although it might become a performance issue if you are dealing with lots of objects/big objects.

**Comment by fayebutler** [comment]
Thanks for your help @p-j that sounds like a good solution :)
