### ISSUE TITLE
Should empty arrays be preserved on their entity?

### ISSUE THREAD

**Issue by babsonmatt** [paularmstrong/normalizr#54]
{ id: 1, name: 'test', tags: [] } normalizes as { id: 1, name: 'test' }

Would it make sense to preserve the empty array or at least allow the option to do so?

**Comment by smargh** [comment]
This problem of dropping empty value keys pertains to objects as well. The problem is not with simply empty values tho; the issue only arises when you have defined an association on an entity, and the association value is empty.

So, `normalize({ id: 1, name: 'test', tags: [] }, entitySchema);` won't drop the empty `tags` array unless you have defined an association for tags, something like:
```
entitySchema.define({
  tags: tagSchema
});
```

In that case, an empty array or an empty object would be dropped from the normalized output.

**Comment by smargh** [comment]
In my testing, this can be remedied by changing the return of the `visitEntity` function in `index.js` from
```
return id;
```
to 
```
return id || {};
```
As, in the case of empty objects, the `id` will be `undefined`.

**Comment by EyePulp** [comment]
Returning an empty object by default does make more sense when someone takes the time to add the key to the source data, even if they're providing empty array.  Otherwise it just silently disappears and isn't available for partial entity updates later on (the key being undefined).

**Comment by unindented** [comment]
@smargh care to create a PR with unit tests?

**Comment by smargh** [comment]
Yes. I'll do it this week.
