### ISSUE TITLE
Keep consistency for relations

### ISSUE THREAD

**Issue by YoruNoHikage** [paularmstrong/normalizr#70]
I think it would be great to have consistency in relationship between entities when normalized.
Here's an example : 

Consider you have two entities **user** and **project**. You define the relations like this (bidirectional) : 

``` js
userSchema.define({
  projects: arrayOf(projectSchema),
})

projectSchema.define({
  contributors: arrayOf(userSchema),
})
```

Now you want to create a project, you send some request to a server that replies with the project entity like this : 

``` js
{
  id: 80,
  contributors: [1], // your userId for example
  // other fields
}
```

You normalize the response and merge with the rest of your entities (just like the real-world example for Redux), the projects' entities are updated but not the user.

So my proposal is to add a capability of telling what is the property in the foreign object and instead of normalizing like this : 

``` js
{
  entities: {
    projects: {
      80: {
        id: 80,
        contributors: [1],
        // other fields
      }
    }
  }
}
```

I'm proposing something like this : 

``` js
{
  entities: {
    projects: {
      80: {
        id: 80,
        contributors: [1],
        // other fields
      }
    },
    users: {
      1: {
         id: 1,
         projects: [80]
       }
    }
  }
}
```

We could do something like this : 

``` js
userSchema.define({
  projects: arrayOf(projectSchema).mappedBy('contributors'),
})

projectSchema.define({
  contributors: arrayOf(userSchema).mappedBy('projects'),
})
```

This prevent any flaws in consistency while being simple (user side). I already tried a solution, it's not bulletproof but I can submit a cleaner PR if you're interested.

**Comment by tokenvolt** [comment]
@YoruNoHikage I was thinking about the same feature, this is really would be very convenient.

**Comment by lukekarrys** [comment]
I found myself needing this as well. Just to test I dropped in @YoruNoHikage's fork in my project and it worked exactly how I wanted it to for my simple case (which was pretty similar to users+projects). I think this would be a great PR.

**Comment by MicheleBertoli** [comment]
@YoruNoHikage we started using your fork too (great job!), you should definitely submit a PR please.

**Comment by YoruNoHikage** [comment]
Thanks, I'll clean the code a bit before submitting it. ;)

**Comment by bpartridge** [comment]
I'd love to see something like this reach maturity! 

Another option is e.g. filtering the values of the entire `entities.contributors` object for ones where `.projects` contains the current project ID in question. Reduces the amount of redundant state (and therefore simplifies the need to keep things in sync), but that's also linear time with the number of connections overall (not just for this company or project), which may or may not be a dealbreaker. Or you can store the results array in a separate part of state (with union, as below).

@YoruNoHikage does your fork account for what happens if two separate actions add to the list of children? i.e. if you receive children 1,2 with parent A, then receive children 3,4 with parent A, would the parent A entity have {children: [3,4]} or {children: [1,2,3,4]} taking the union of the ids? 

Union makes sense to me - either way, this should be documented and tested before PR I think! If you don't have union, that can easily be brittle i.e. if multiple results are streaming in out of order, i.e. you click an async pagination bar and the first page comes back after the second.

N.B. whether you're filtering or using this mappedBy functionality, if you intend to be able to delete items or change their relationships, you'll likely need to add a separate reducer on your entities that updates all the places where the relationship would be read. ORM isn't easy, and we should all be working on documentation so that we get in front of leaks in the abstraction!

**Comment by YoruNoHikage** [comment]
Currently, I use Normalizr just like in the Redux Real World example. You first get and dispatch `{children: [1,2]}` and then `{children: [3,4]}`. Then, the reducer does its job : 
```
function entities(state, action) {
  if (action.response && action.response.entities) {
    return merge({}, state, action.response.entities)
  }

  return state
}
```
You get `{children: [1,2,3,4]}` but it's up to you to do it differently in your reducers.

**Comment by bpartridge** [comment]
Ah, right! I'd forgotten for a moment that merging is outside the scope of normalizr itself, which is only worried about the transformation of each response independent of state! Reverse relations do make the merging a bit more complicated for real use cases (you'd probably want some entity-specific logic), and it's worth a brief note in the wiki or readme here, but that can be done separately from this PR!

**Comment by unindented** [comment]
The PR has been merged. Thank you @YoruNoHikage!

**Comment by gaearon** [comment]
I reverted the PR for now, please contribute to discussion here: https://github.com/gaearon/normalizr/pull/80#issuecomment-206957386

**Comment by paularmstrong** [comment]
I've spread this around to a couple of PRs already. Submitting here for community feedback as well:

Normalizr v3 (v3.0.0-alpha.5 on npm) has a bit more open functionality that allows schema authors to define this kind of processing. It's a bit more work than just having some built-in `mappedBy` or `relationshipOf` functions, but it's more explicit and allows developers to handle their relational edge cases a bit easier.

Here's a short [example](https://github.com/paularmstrong/normalizr/tree/c85dfa0d7924fe2fbcbf526ffd5cbd0a3819f672/examples/relationships) of what's possible using the `processStrategy` and `mergeStrategy` functions available in v3.
