### ISSUE TITLE
How should "belongs to" relations be kept up to date?

### ISSUE THREAD

**Issue by donpinkus** [paularmstrong/normalizr#81]
Lets say I have two models, **Users** and **Posts**. A user has many posts.

```
const user = new Schema('users');
const post = new Schema('posts');

user.define({
  posts: arrayOf(post)
});
```

When a user creates a new post, our API call responds with the JSON representing the new post:

```
entities: {
  posts:  {
    123: {
      user_id: 3,
      title: "How to use Normalizr",
      content: "A great library for normalizing your data."
    }
  }
},
result: 123
```

This is great for updating my store's `entities.posts`, however now my `entities.users[3].posts` is out of date since it doesn't have this new post. 

What is the correct way to keep the user's posts up to date?

This seems similar to #70, except extra declarations seem unnecessary since we know the relationship.

**Comment by RaitoBezarius** [comment]
My approach to this problem is to takes the `result` IDs and concatenate it to the correct field of my data structure.

What helps a lot is that I have some metadata about how should I process those results, basically it's something like this:

(redux context)
```js
const createPost = (title, content) => dispatch => {
  // Let's assume that the authenticated user is creating the post.
  const userId = getCurrentUser().id
  return dispatch(WebAPI.createPost({title, content}))
  .then(resp => resp.data)
  .then(data => normalize(data, PostSchema))
  .then(({entities, result} => dispatch(receivePosts(entities, result)))
  .then(postIds => dispatch(receiveId('users', userId, 'posts', postIds)))
}
```

`receiveId` reducer could be implemented like the following:
```js
function handleNewID (state, entityKey, entityIds) {
  return {
    ...state,
    [entityKey]: [...state[entityKey], ...entityIds]
  }
}

// some reducer code
function reduceNewID (state, action) {
   // containerKey = 'users'
  // containerId = userId
  handleNewID(state[action.containerKey][action.containerId], action.entityKey, action.entityIds)
}
```

But well, it could be a bad approach, I know it works quite good, and it could be a lot more improved using `combineReducers`. What I hate with this is that I require that `receiveId` is somehow verbose about how to update it.

You could combine this with ImmutableJS.

What do you think?
