### ISSUE TITLE
Shouldn't `normalize(...).entities` return results in same order of input

### ISSUE THREAD

**Issue by rafaelsales** [paularmstrong/normalizr#93]
I need to read the records in the same order they are sent from server. Shouldn't `.entities` method return an ordered map rather than an object, which can't keep order?

**Comment by paularmstrong** [comment]
Ordered maps don't exist in JavaScript. Are you looking for an ordered array?

There are multiple reasons this isn't done:
* If the same entity is come across more than once, they are merged together so you only get one
* Entities are keyed by their ID so that you don't need to extract that again when using later
* The value of `result` should be an ordered array of IDs, if you normalized with `arrayOf`

A little more context with your input and schema might help me better understand your question.
